/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_subjoin_mosd_ArchiveInspector */

#ifndef _Included_net_subjoin_mosd_ArchiveInspector
#define _Included_net_subjoin_mosd_ArchiveInspector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_subjoin_mosd_ArchiveInspector
 * Method:    getContents
 * Signature: (Ljava/lang/String;)[Lnet/subjoin/mosd/DistributionFile;
 */
JNIEXPORT jobjectArray JNICALL Java_net_subjoin_mosd_ArchiveInspector_getContents
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
