#!/bin/bash

OPTS=()

while [ "${1:0:1}" = "-" ]; do
    OPTS=("${OPTS[@]}" "${1}")
    shift
done

if [ -f "${1}" ]; then
     CLASS="${1%.java}"
     CLASS="${CLASS#src/}"
 else
    CLASS="net.subjoin.mosd.${1}"
fi
shift

DIR="$(dirname -- "${0}")"

exec "${DIR}/javatool" java "${OPTS[@]}" "${CLASS}" "${@}"

