#!/bin/bash

if [ -f "${1}" ]; then
     CLASS="${1%.java}"
     CLASS="${CLASS#src/}"
 else
    CLASS="net.subjoin.mosd.${1}"
fi
shift

DIR="$(dirname -- "${0}")"

exec "${DIR}/javatool" java "${CLASS}" "${@}"

